# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun Dec 15 19:49:30 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 774)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.ClassesWidget = QtGui.QWidget(MainWindow)
        self.ClassesWidget.setObjectName("ClassesWidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.ClassesWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ClassesLabel = QtGui.QLabel(self.ClassesWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.ClassesLabel.setFont(font)
        self.ClassesLabel.setObjectName("ClassesLabel")
        self.gridLayout_4.addWidget(self.ClassesLabel, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ClassesAddSiblingButton = QtGui.QPushButton(self.ClassesWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClassesAddSiblingButton.sizePolicy().hasHeightForWidth())
        self.ClassesAddSiblingButton.setSizePolicy(sizePolicy)
        self.ClassesAddSiblingButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/images/img/application_side_expand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClassesAddSiblingButton.setIcon(icon)
        self.ClassesAddSiblingButton.setObjectName("ClassesAddSiblingButton")
        self.horizontalLayout.addWidget(self.ClassesAddSiblingButton)
        self.ClassesAddChildButton = QtGui.QPushButton(self.ClassesWidget)
        self.ClassesAddChildButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClassesAddChildButton.sizePolicy().hasHeightForWidth())
        self.ClassesAddChildButton.setSizePolicy(sizePolicy)
        self.ClassesAddChildButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/images/img/application_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClassesAddChildButton.setIcon(icon1)
        self.ClassesAddChildButton.setObjectName("ClassesAddChildButton")
        self.horizontalLayout.addWidget(self.ClassesAddChildButton)
        self.ClassesEditButton = QtGui.QPushButton(self.ClassesWidget)
        self.ClassesEditButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClassesEditButton.sizePolicy().hasHeightForWidth())
        self.ClassesEditButton.setSizePolicy(sizePolicy)
        self.ClassesEditButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main/images/img/application_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClassesEditButton.setIcon(icon2)
        self.ClassesEditButton.setObjectName("ClassesEditButton")
        self.horizontalLayout.addWidget(self.ClassesEditButton)
        self.ClassesInsertValuesButton = QtGui.QPushButton(self.ClassesWidget)
        self.ClassesInsertValuesButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(23)
        sizePolicy.setVerticalStretch(22)
        sizePolicy.setHeightForWidth(self.ClassesInsertValuesButton.sizePolicy().hasHeightForWidth())
        self.ClassesInsertValuesButton.setSizePolicy(sizePolicy)
        self.ClassesInsertValuesButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/main/images/img/coins_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClassesInsertValuesButton.setIcon(icon3)
        self.ClassesInsertValuesButton.setObjectName("ClassesInsertValuesButton")
        self.horizontalLayout.addWidget(self.ClassesInsertValuesButton)
        self.ClassesRemoveButton = QtGui.QToolButton(self.ClassesWidget)
        self.ClassesRemoveButton.setEnabled(False)
        self.ClassesRemoveButton.setAutoFillBackground(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/main/images/img/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClassesRemoveButton.setIcon(icon4)
        self.ClassesRemoveButton.setArrowType(QtCore.Qt.NoArrow)
        self.ClassesRemoveButton.setObjectName("ClassesRemoveButton")
        self.horizontalLayout.addWidget(self.ClassesRemoveButton)
        self.ClassesExpandCollapseButton = QtGui.QToolButton(self.ClassesWidget)
        self.ClassesExpandCollapseButton.setEnabled(False)
        self.ClassesExpandCollapseButton.setAutoFillBackground(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/main/images/img/chart_organisation_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/main/images/img/chart_organisation_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.ClassesExpandCollapseButton.setIcon(icon5)
        self.ClassesExpandCollapseButton.setCheckable(True)
        self.ClassesExpandCollapseButton.setArrowType(QtCore.Qt.NoArrow)
        self.ClassesExpandCollapseButton.setObjectName("ClassesExpandCollapseButton")
        self.horizontalLayout.addWidget(self.ClassesExpandCollapseButton)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.ClassesTree = QtGui.QTreeWidget(self.ClassesWidget)
        self.ClassesTree.setAcceptDrops(True)
        self.ClassesTree.setDragEnabled(False)
        self.ClassesTree.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.ClassesTree.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.ClassesTree.setRootIsDecorated(True)
        self.ClassesTree.setHeaderHidden(False)
        self.ClassesTree.setObjectName("ClassesTree")
        self.ClassesTree.header().setDefaultSectionSize(100)
        self.ClassesTree.header().setMinimumSectionSize(20)
        self.gridLayout_4.addWidget(self.ClassesTree, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.ClassesWidget)
        self.MenuBar = QtGui.QMenuBar(MainWindow)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 940, 21))
        self.MenuBar.setObjectName("MenuBar")
        self.MenuFile = QtGui.QMenu(self.MenuBar)
        self.MenuFile.setObjectName("MenuFile")
        self.menOpen_Recent = QtGui.QMenu(self.MenuFile)
        self.menOpen_Recent.setObjectName("menOpen_Recent")
        self.MenuHelp = QtGui.QMenu(self.MenuBar)
        self.MenuHelp.setObjectName("MenuHelp")
        self.MenuImport = QtGui.QMenu(self.MenuBar)
        self.MenuImport.setEnabled(False)
        self.MenuImport.setObjectName("MenuImport")
        self.MenuView = QtGui.QMenu(self.MenuBar)
        self.MenuView.setObjectName("MenuView")
        MainWindow.setMenuBar(self.MenuBar)
        self.ToolBar = QtGui.QToolBar(MainWindow)
        self.ToolBar.setObjectName("ToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.ToolBar)
        self.ValuesDock = QtGui.QDockWidget(MainWindow)
        self.ValuesDock.setMinimumSize(QtCore.QSize(509, 368))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.ValuesDock.setFont(font)
        self.ValuesDock.setObjectName("ValuesDock")
        self.ValuesDockContents = QtGui.QWidget()
        self.ValuesDockContents.setObjectName("ValuesDockContents")
        self.gridLayout = QtGui.QGridLayout(self.ValuesDockContents)
        self.gridLayout.setObjectName("gridLayout")
        self.ValuesButtonsHorizontalLayout = QtGui.QHBoxLayout()
        self.ValuesButtonsHorizontalLayout.setObjectName("ValuesButtonsHorizontalLayout")
        self.ValuesAddButton = QtGui.QPushButton(self.ValuesDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ValuesAddButton.sizePolicy().hasHeightForWidth())
        self.ValuesAddButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setWeight(50)
        font.setBold(False)
        self.ValuesAddButton.setFont(font)
        self.ValuesAddButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/main/images/img/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ValuesAddButton.setIcon(icon6)
        self.ValuesAddButton.setObjectName("ValuesAddButton")
        self.ValuesButtonsHorizontalLayout.addWidget(self.ValuesAddButton)
        self.ValuesRemoveButton = QtGui.QPushButton(self.ValuesDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ValuesRemoveButton.sizePolicy().hasHeightForWidth())
        self.ValuesRemoveButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setWeight(75)
        font.setBold(True)
        self.ValuesRemoveButton.setFont(font)
        self.ValuesRemoveButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/main/images/img/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ValuesRemoveButton.setIcon(icon7)
        self.ValuesRemoveButton.setCheckable(False)
        self.ValuesRemoveButton.setFlat(False)
        self.ValuesRemoveButton.setObjectName("ValuesRemoveButton")
        self.ValuesButtonsHorizontalLayout.addWidget(self.ValuesRemoveButton)
        self.ValuesIncludeAllButton = QtGui.QPushButton(self.ValuesDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ValuesIncludeAllButton.sizePolicy().hasHeightForWidth())
        self.ValuesIncludeAllButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setWeight(50)
        font.setBold(False)
        self.ValuesIncludeAllButton.setFont(font)
        self.ValuesIncludeAllButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/main/images/img/excluded.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ValuesIncludeAllButton.setIcon(icon8)
        self.ValuesIncludeAllButton.setObjectName("ValuesIncludeAllButton")
        self.ValuesButtonsHorizontalLayout.addWidget(self.ValuesIncludeAllButton)
        self.gridLayout.addLayout(self.ValuesButtonsHorizontalLayout, 0, 0, 1, 1)
        self.ValueTableWidget = QtGui.QTableWidget(self.ValuesDockContents)
        self.ValueTableWidget.setEnabled(True)
        self.ValueTableWidget.setDragEnabled(True)
        self.ValueTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.ValueTableWidget.setShowGrid(True)
        self.ValueTableWidget.setObjectName("ValueTableWidget")
        self.ValueTableWidget.setColumnCount(0)
        self.ValueTableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.ValueTableWidget, 1, 0, 1, 1)
        self.ValuesDock.setWidget(self.ValuesDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.ValuesDock)
        self.CoefficientDock = QtGui.QDockWidget(MainWindow)
        self.CoefficientDock.setMinimumSize(QtCore.QSize(509, 172))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.CoefficientDock.setFont(font)
        self.CoefficientDock.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.CoefficientDock.setObjectName("CoefficientDock")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ValuesButtonsHorizontalLayout_3 = QtGui.QHBoxLayout()
        self.ValuesButtonsHorizontalLayout_3.setObjectName("ValuesButtonsHorizontalLayout_3")
        self.CoefficientAddButton = QtGui.QPushButton(self.dockWidgetContents)
        self.CoefficientAddButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CoefficientAddButton.sizePolicy().hasHeightForWidth())
        self.CoefficientAddButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setWeight(50)
        font.setBold(False)
        self.CoefficientAddButton.setFont(font)
        self.CoefficientAddButton.setText("")
        self.CoefficientAddButton.setIcon(icon6)
        self.CoefficientAddButton.setObjectName("CoefficientAddButton")
        self.ValuesButtonsHorizontalLayout_3.addWidget(self.CoefficientAddButton)
        self.CoefficientRemoveButton = QtGui.QPushButton(self.dockWidgetContents)
        self.CoefficientRemoveButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CoefficientRemoveButton.sizePolicy().hasHeightForWidth())
        self.CoefficientRemoveButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setWeight(75)
        font.setBold(True)
        self.CoefficientRemoveButton.setFont(font)
        self.CoefficientRemoveButton.setText("")
        self.CoefficientRemoveButton.setIcon(icon7)
        self.CoefficientRemoveButton.setObjectName("CoefficientRemoveButton")
        self.ValuesButtonsHorizontalLayout_3.addWidget(self.CoefficientRemoveButton)
        self.gridLayout_2.addLayout(self.ValuesButtonsHorizontalLayout_3, 0, 0, 1, 1)
        self.CoefficientTableWidget = QtGui.QTableWidget(self.dockWidgetContents)
        self.CoefficientTableWidget.setObjectName("CoefficientTableWidget")
        self.CoefficientTableWidget.setColumnCount(0)
        self.CoefficientTableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.CoefficientTableWidget, 1, 0, 1, 1)
        self.CoefficientDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.CoefficientDock)
        self.MetadataDock = QtGui.QDockWidget(MainWindow)
        self.MetadataDock.setMinimumSize(QtCore.QSize(509, 177))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.MetadataDock.setFont(font)
        self.MetadataDock.setObjectName("MetadataDock")
        self.MetadataDockContents = QtGui.QWidget()
        self.MetadataDockContents.setObjectName("MetadataDockContents")
        self.gridLayout_3 = QtGui.QGridLayout(self.MetadataDockContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.MetadataNameLabel = QtGui.QLabel(self.MetadataDockContents)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.MetadataNameLabel.setFont(font)
        self.MetadataNameLabel.setObjectName("MetadataNameLabel")
        self.gridLayout_3.addWidget(self.MetadataNameLabel, 0, 0, 1, 1)
        self.MetadataNameLineEdit = QtGui.QLineEdit(self.MetadataDockContents)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.MetadataNameLineEdit.setFont(font)
        self.MetadataNameLineEdit.setObjectName("MetadataNameLineEdit")
        self.gridLayout_3.addWidget(self.MetadataNameLineEdit, 1, 0, 1, 1)
        self.MetadataDescriptionLabel = QtGui.QLabel(self.MetadataDockContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(50)
        font.setBold(False)
        self.MetadataDescriptionLabel.setFont(font)
        self.MetadataDescriptionLabel.setObjectName("MetadataDescriptionLabel")
        self.gridLayout_3.addWidget(self.MetadataDescriptionLabel, 2, 0, 1, 1)
        self.MetadataDescriptionTextEdit = QtGui.QPlainTextEdit(self.MetadataDockContents)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.MetadataDescriptionTextEdit.setFont(font)
        self.MetadataDescriptionTextEdit.setObjectName("MetadataDescriptionTextEdit")
        self.gridLayout_3.addWidget(self.MetadataDescriptionTextEdit, 3, 0, 1, 1)
        self.MetadataDock.setWidget(self.MetadataDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.MetadataDock)
        self.ActionNew = QtGui.QAction(MainWindow)
        self.ActionNew.setObjectName("ActionNew")
        self.ActionOpen = QtGui.QAction(MainWindow)
        self.ActionOpen.setObjectName("ActionOpen")
        self.ActionSave = QtGui.QAction(MainWindow)
        self.ActionSave.setObjectName("ActionSave")
        self.ActionQuit = QtGui.QAction(MainWindow)
        self.ActionQuit.setObjectName("ActionQuit")
        self.ActionSaveAs = QtGui.QAction(MainWindow)
        self.ActionSaveAs.setObjectName("ActionSaveAs")
        self.ActionImportFromRaster = QtGui.QAction(MainWindow)
        self.ActionImportFromRaster.setObjectName("ActionImportFromRaster")
        self.ActionImportFromLcc = QtGui.QAction(MainWindow)
        self.ActionImportFromLcc.setObjectName("ActionImportFromLcc")
        self.ActionHelp = QtGui.QAction(MainWindow)
        self.ActionHelp.setObjectName("ActionHelp")
        self.ActionAbout = QtGui.QAction(MainWindow)
        self.ActionAbout.setObjectName("ActionAbout")
        self.ActionValuesShowHide = QtGui.QAction(MainWindow)
        self.ActionValuesShowHide.setCheckable(True)
        self.ActionValuesShowHide.setChecked(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/main/images/img/coins.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ActionValuesShowHide.setIcon(icon9)
        self.ActionValuesShowHide.setObjectName("ActionValuesShowHide")
        self.ActionMetadataShowHide = QtGui.QAction(MainWindow)
        self.ActionMetadataShowHide.setCheckable(True)
        self.ActionMetadataShowHide.setChecked(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/main/images/img/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ActionMetadataShowHide.setIcon(icon10)
        self.ActionMetadataShowHide.setObjectName("ActionMetadataShowHide")
        self.ActionCoefficientShowHide = QtGui.QAction(MainWindow)
        self.ActionCoefficientShowHide.setCheckable(True)
        self.ActionCoefficientShowHide.setChecked(True)
        self.ActionCoefficientShowHide.setIcon(icon3)
        self.ActionCoefficientShowHide.setObjectName("ActionCoefficientShowHide")
        self.ActionRestore_AutoSave = QtGui.QAction(MainWindow)
        self.ActionRestore_AutoSave.setEnabled(True)
        self.ActionRestore_AutoSave.setObjectName("ActionRestore_AutoSave")
        self.ActionValues_Dock = QtGui.QAction(MainWindow)
        self.ActionValues_Dock.setCheckable(True)
        self.ActionValues_Dock.setChecked(True)
        self.ActionValues_Dock.setObjectName("ActionValues_Dock")
        self.ActionCoefficient_Dock = QtGui.QAction(MainWindow)
        self.ActionCoefficient_Dock.setCheckable(True)
        self.ActionCoefficient_Dock.setChecked(True)
        self.ActionCoefficient_Dock.setObjectName("ActionCoefficient_Dock")
        self.ActionMetadata_Dock = QtGui.QAction(MainWindow)
        self.ActionMetadata_Dock.setCheckable(True)
        self.ActionMetadata_Dock.setChecked(True)
        self.ActionMetadata_Dock.setObjectName("ActionMetadata_Dock")
        self.actionNone = QtGui.QAction(MainWindow)
        self.actionNone.setObjectName("actionNone")
        self.menOpen_Recent.addAction(self.actionNone)
        self.MenuFile.addAction(self.ActionNew)
        self.MenuFile.addAction(self.ActionOpen)
        self.MenuFile.addAction(self.menOpen_Recent.menuAction())
        self.MenuFile.addAction(self.ActionRestore_AutoSave)
        self.MenuFile.addSeparator()
        self.MenuFile.addAction(self.ActionSave)
        self.MenuFile.addAction(self.ActionSaveAs)
        self.MenuFile.addSeparator()
        self.MenuFile.addAction(self.ActionQuit)
        self.MenuHelp.addAction(self.ActionHelp)
        self.MenuHelp.addSeparator()
        self.MenuHelp.addAction(self.ActionAbout)
        self.MenuImport.addAction(self.ActionImportFromRaster)
        self.MenuView.addAction(self.ActionValues_Dock)
        self.MenuView.addAction(self.ActionCoefficient_Dock)
        self.MenuView.addAction(self.ActionMetadata_Dock)
        self.MenuBar.addAction(self.MenuFile.menuAction())
        self.MenuBar.addAction(self.MenuView.menuAction())
        self.MenuBar.addAction(self.MenuImport.menuAction())
        self.MenuBar.addAction(self.MenuHelp.menuAction())
        self.ToolBar.addAction(self.ActionValuesShowHide)
        self.ToolBar.addAction(self.ActionMetadataShowHide)
        self.ToolBar.addAction(self.ActionCoefficientShowHide)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.ActionValuesShowHide, QtCore.SIGNAL("triggered(bool)"), self.ValuesDock.setVisible)
        QtCore.QObject.connect(self.ActionMetadataShowHide, QtCore.SIGNAL("triggered(bool)"), self.MetadataDock.setVisible)
        QtCore.QObject.connect(self.ActionCoefficientShowHide, QtCore.SIGNAL("triggered(bool)"), self.CoefficientDock.setVisible)
        QtCore.QObject.connect(self.ValuesDock, QtCore.SIGNAL("visibilityChanged(bool)"), self.ActionValuesShowHide.setChecked)
        QtCore.QObject.connect(self.CoefficientDock, QtCore.SIGNAL("visibilityChanged(bool)"), self.ActionCoefficientShowHide.setChecked)
        QtCore.QObject.connect(self.MetadataDock, QtCore.SIGNAL("visibilityChanged(bool)"), self.ActionMetadataShowHide.setChecked)
        QtCore.QObject.connect(self.ActionValues_Dock, QtCore.SIGNAL("triggered(bool)"), self.ValuesDock.setVisible)
        QtCore.QObject.connect(self.ActionValuesShowHide, QtCore.SIGNAL("triggered(bool)"), self.ActionValues_Dock.setChecked)
        QtCore.QObject.connect(self.ActionCoefficient_Dock, QtCore.SIGNAL("triggered(bool)"), self.CoefficientDock.setVisible)
        QtCore.QObject.connect(self.ActionCoefficientShowHide, QtCore.SIGNAL("triggered(bool)"), self.ActionCoefficient_Dock.setChecked)
        QtCore.QObject.connect(self.ActionMetadata_Dock, QtCore.SIGNAL("triggered(bool)"), self.MetadataDock.setVisible)
        QtCore.QObject.connect(self.ActionMetadataShowHide, QtCore.SIGNAL("triggered(bool)"), self.ActionMetadata_Dock.setChecked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.MetadataNameLineEdit, self.MetadataDescriptionTextEdit)
        MainWindow.setTabOrder(self.MetadataDescriptionTextEdit, self.ClassesAddChildButton)
        MainWindow.setTabOrder(self.ClassesAddChildButton, self.ClassesEditButton)
        MainWindow.setTabOrder(self.ClassesEditButton, self.ClassesRemoveButton)
        MainWindow.setTabOrder(self.ClassesRemoveButton, self.ClassesTree)
        MainWindow.setTabOrder(self.ClassesTree, self.ClassesAddSiblingButton)
        MainWindow.setTabOrder(self.ClassesAddSiblingButton, self.ValuesAddButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Land Cover Classification Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesLabel.setText(QtGui.QApplication.translate("MainWindow", "CLASSES", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesAddSiblingButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Start Tree/Add Sibling Class (Alt+S)", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesAddSiblingButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+S", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesAddChildButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Add Child Class (Alt+C)", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesAddChildButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesEditButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Edit Class (Alt+E)", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesEditButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+E", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesInsertValuesButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Insert Values (Alt+I)", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesInsertValuesButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+I", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesRemoveButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove Class/Value (Alt+D)", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesRemoveButton.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesRemoveButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+D", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesExpandCollapseButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Expand/Collapse (Alt+T)", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesExpandCollapseButton.setText(QtGui.QApplication.translate("MainWindow", "Expand/Collapse", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesExpandCollapseButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+T", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.setSortingEnabled(True)
        self.ClassesTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Class", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.MenuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menOpen_Recent.setTitle(QtGui.QApplication.translate("MainWindow", "Open Recent", None, QtGui.QApplication.UnicodeUTF8))
        self.MenuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.MenuImport.setTitle(QtGui.QApplication.translate("MainWindow", "&Import", None, QtGui.QApplication.UnicodeUTF8))
        self.MenuView.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolBar.setToolTip(QtGui.QApplication.translate("MainWindow", "Show/Hide Values", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "VALUES", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesAddButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Add Value (Ctrl+A)", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesAddButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesRemoveButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove Value (Ctrl+D)", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesRemoveButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesIncludeAllButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Deselect Exclusion (Ctrl+I)", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesIncludeAllButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.CoefficientDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "COEFFICIENTS", None, QtGui.QApplication.UnicodeUTF8))
        self.CoefficientAddButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Add Coefficients", None, QtGui.QApplication.UnicodeUTF8))
        self.CoefficientRemoveButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove Coefficients", None, QtGui.QApplication.UnicodeUTF8))
        self.MetadataDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "METADATA", None, QtGui.QApplication.UnicodeUTF8))
        self.MetadataNameLabel.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.MetadataDescriptionLabel.setText(QtGui.QApplication.translate("MainWindow", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionNew.setText(QtGui.QApplication.translate("MainWindow", "&New...", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionSaveAs.setShortcut(QtGui.QApplication.translate("MainWindow", "F12", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionImportFromRaster.setText(QtGui.QApplication.translate("MainWindow", "From Raster...", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionImportFromLcc.setText(QtGui.QApplication.translate("MainWindow", "From LCC File...", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionHelp.setText(QtGui.QApplication.translate("MainWindow", "LCCEditor &Help", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionAbout.setText(QtGui.QApplication.translate("MainWindow", "About LCCEditor", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionValuesShowHide.setText(QtGui.QApplication.translate("MainWindow", "Show/Hide Values", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionMetadataShowHide.setText(QtGui.QApplication.translate("MainWindow", "Show/Hide Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionCoefficientShowHide.setText(QtGui.QApplication.translate("MainWindow", "ActionCoefficientShowHide", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionCoefficientShowHide.setToolTip(QtGui.QApplication.translate("MainWindow", "Show/Hide Coefficients", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionRestore_AutoSave.setText(QtGui.QApplication.translate("MainWindow", "&Restore AutoSave", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionRestore_AutoSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionValues_Dock.setText(QtGui.QApplication.translate("MainWindow", "Show/Hide Values Dock", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionValues_Dock.setToolTip(QtGui.QApplication.translate("MainWindow", "Show/Hide Values Dock", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionCoefficient_Dock.setText(QtGui.QApplication.translate("MainWindow", "Show/Hide Coefficient Dock", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionCoefficient_Dock.setToolTip(QtGui.QApplication.translate("MainWindow", "Show/Hide Coefficient Dock", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionMetadata_Dock.setText(QtGui.QApplication.translate("MainWindow", "Show/Hide Metadata Dock", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionMetadata_Dock.setToolTip(QtGui.QApplication.translate("MainWindow", "Show/Hide Metadata Dock", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNone.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))

import main_rc
