# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created: Tue Apr 03 21:16:13 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 774)
        self.ClassesWidget = QtGui.QWidget(MainWindow)
        self.ClassesWidget.setObjectName("ClassesWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.ClassesWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ClassesLabel = QtGui.QLabel(self.ClassesWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.ClassesLabel.setFont(font)
        self.ClassesLabel.setObjectName("ClassesLabel")
        self.verticalLayout_4.addWidget(self.ClassesLabel)
        self.ClassesButtonsHorizontalLayout = QtGui.QHBoxLayout()
        self.ClassesButtonsHorizontalLayout.setObjectName("ClassesButtonsHorizontalLayout")
        self.ClassesInsertValuesButton = QtGui.QPushButton(self.ClassesWidget)
        self.ClassesInsertValuesButton.setObjectName("ClassesInsertValuesButton")
        self.ClassesButtonsHorizontalLayout.addWidget(self.ClassesInsertValuesButton)
        self.ClassesAddSiblingButton = QtGui.QToolButton(self.ClassesWidget)
        self.ClassesAddSiblingButton.setObjectName("ClassesAddSiblingButton")
        self.ClassesButtonsHorizontalLayout.addWidget(self.ClassesAddSiblingButton)
        self.ClassesAddChildButton = QtGui.QToolButton(self.ClassesWidget)
        self.ClassesAddChildButton.setObjectName("ClassesAddChildButton")
        self.ClassesButtonsHorizontalLayout.addWidget(self.ClassesAddChildButton)
        self.ClassesEditButton = QtGui.QToolButton(self.ClassesWidget)
        self.ClassesEditButton.setObjectName("ClassesEditButton")
        self.ClassesButtonsHorizontalLayout.addWidget(self.ClassesEditButton)
        self.ClassesRemoveButton = QtGui.QToolButton(self.ClassesWidget)
        self.ClassesRemoveButton.setAutoFillBackground(False)
        self.ClassesRemoveButton.setArrowType(QtCore.Qt.NoArrow)
        self.ClassesRemoveButton.setObjectName("ClassesRemoveButton")
        self.ClassesButtonsHorizontalLayout.addWidget(self.ClassesRemoveButton)
        self.verticalLayout_4.addLayout(self.ClassesButtonsHorizontalLayout)
        self.ClassesTree = QtGui.QTreeWidget(self.ClassesWidget)
        self.ClassesTree.setRootIsDecorated(True)
        self.ClassesTree.setHeaderHidden(False)
        self.ClassesTree.setObjectName("ClassesTree")
        item_0 = QtGui.QTreeWidgetItem(self.ClassesTree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.ClassesTree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.ClassesTree.header().setDefaultSectionSize(100)
        self.ClassesTree.header().setMinimumSectionSize(20)
        self.verticalLayout_4.addWidget(self.ClassesTree)
        MainWindow.setCentralWidget(self.ClassesWidget)
        self.MenuBar = QtGui.QMenuBar(MainWindow)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 940, 18))
        self.MenuBar.setObjectName("MenuBar")
        self.MenuFile = QtGui.QMenu(self.MenuBar)
        self.MenuFile.setObjectName("MenuFile")
        self.MenuHelp = QtGui.QMenu(self.MenuBar)
        self.MenuHelp.setObjectName("MenuHelp")
        self.MenuImport = QtGui.QMenu(self.MenuBar)
        self.MenuImport.setObjectName("MenuImport")
        MainWindow.setMenuBar(self.MenuBar)
        self.ValuesDock = QtGui.QDockWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.ValuesDock.setFont(font)
        self.ValuesDock.setObjectName("ValuesDock")
        self.ValuesDockContents = QtGui.QWidget()
        self.ValuesDockContents.setObjectName("ValuesDockContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.ValuesDockContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ValuesButtonsHorizontalLayout = QtGui.QHBoxLayout()
        self.ValuesButtonsHorizontalLayout.setObjectName("ValuesButtonsHorizontalLayout")
        self.ValuesIncludeButton = QtGui.QToolButton(self.ValuesDockContents)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.ValuesIncludeButton.setFont(font)
        self.ValuesIncludeButton.setObjectName("ValuesIncludeButton")
        self.ValuesButtonsHorizontalLayout.addWidget(self.ValuesIncludeButton)
        self.ValuesExcludeButton = QtGui.QToolButton(self.ValuesDockContents)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.ValuesExcludeButton.setFont(font)
        self.ValuesExcludeButton.setAutoFillBackground(False)
        self.ValuesExcludeButton.setArrowType(QtCore.Qt.NoArrow)
        self.ValuesExcludeButton.setObjectName("ValuesExcludeButton")
        self.ValuesButtonsHorizontalLayout.addWidget(self.ValuesExcludeButton)
        self.ValuesAddButton = QtGui.QToolButton(self.ValuesDockContents)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.ValuesAddButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/images/img/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ValuesAddButton.setIcon(icon)
        self.ValuesAddButton.setObjectName("ValuesAddButton")
        self.ValuesButtonsHorizontalLayout.addWidget(self.ValuesAddButton)
        self.ValuesRemoveButton = QtGui.QToolButton(self.ValuesDockContents)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.ValuesRemoveButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/images/img/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ValuesRemoveButton.setIcon(icon1)
        self.ValuesRemoveButton.setObjectName("ValuesRemoveButton")
        self.ValuesButtonsHorizontalLayout.addWidget(self.ValuesRemoveButton)
        self.verticalLayout.addLayout(self.ValuesButtonsHorizontalLayout)
        self.ValuesTree = QtGui.QTreeWidget(self.ValuesDockContents)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.ValuesTree.setFont(font)
        self.ValuesTree.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.ValuesTree.setObjectName("ValuesTree")
        item_0 = QtGui.QTreeWidgetItem(self.ValuesTree)
        item_0.setCheckState(2, QtCore.Qt.PartiallyChecked)
        item_0 = QtGui.QTreeWidgetItem(self.ValuesTree)
        item_0.setCheckState(2, QtCore.Qt.PartiallyChecked)
        item_0 = QtGui.QTreeWidgetItem(self.ValuesTree)
        item_0.setCheckState(2, QtCore.Qt.PartiallyChecked)
        item_0 = QtGui.QTreeWidgetItem(self.ValuesTree)
        item_0.setCheckState(2, QtCore.Qt.PartiallyChecked)
        self.ValuesTree.header().setDefaultSectionSize(121)
        self.ValuesTree.header().setMinimumSectionSize(4)
        self.ValuesTree.header().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.ValuesTree)
        self.ValuesDock.setWidget(self.ValuesDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.ValuesDock)
        self.MetadataDock = QtGui.QDockWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.MetadataDock.setFont(font)
        self.MetadataDock.setObjectName("MetadataDock")
        self.MetadataDockContents = QtGui.QWidget()
        self.MetadataDockContents.setObjectName("MetadataDockContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.MetadataDockContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MetadataNameLabel = QtGui.QLabel(self.MetadataDockContents)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.MetadataNameLabel.setFont(font)
        self.MetadataNameLabel.setObjectName("MetadataNameLabel")
        self.verticalLayout_3.addWidget(self.MetadataNameLabel)
        self.MetadataNameLineEdit = QtGui.QLineEdit(self.MetadataDockContents)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.MetadataNameLineEdit.setFont(font)
        self.MetadataNameLineEdit.setObjectName("MetadataNameLineEdit")
        self.verticalLayout_3.addWidget(self.MetadataNameLineEdit)
        self.MetadataDescriptionLabel = QtGui.QLabel(self.MetadataDockContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(50)
        font.setBold(False)
        self.MetadataDescriptionLabel.setFont(font)
        self.MetadataDescriptionLabel.setObjectName("MetadataDescriptionLabel")
        self.verticalLayout_3.addWidget(self.MetadataDescriptionLabel)
        self.MetadataDescriptionTextEdit = QtGui.QPlainTextEdit(self.MetadataDockContents)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.MetadataDescriptionTextEdit.setFont(font)
        self.MetadataDescriptionTextEdit.setObjectName("MetadataDescriptionTextEdit")
        self.verticalLayout_3.addWidget(self.MetadataDescriptionTextEdit)
        self.MetadataDock.setWidget(self.MetadataDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.MetadataDock)
        self.ToolBar = QtGui.QToolBar(MainWindow)
        self.ToolBar.setObjectName("ToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.ToolBar)
        self.ActionNew = QtGui.QAction(MainWindow)
        self.ActionNew.setObjectName("ActionNew")
        self.ActionOpen = QtGui.QAction(MainWindow)
        self.ActionOpen.setObjectName("ActionOpen")
        self.ActionSave = QtGui.QAction(MainWindow)
        self.ActionSave.setObjectName("ActionSave")
        self.ActionQuit = QtGui.QAction(MainWindow)
        self.ActionQuit.setObjectName("ActionQuit")
        self.ActionSaveAs = QtGui.QAction(MainWindow)
        self.ActionSaveAs.setObjectName("ActionSaveAs")
        self.ActionImportFromRaster = QtGui.QAction(MainWindow)
        self.ActionImportFromRaster.setObjectName("ActionImportFromRaster")
        self.ActionImportFromLcc = QtGui.QAction(MainWindow)
        self.ActionImportFromLcc.setObjectName("ActionImportFromLcc")
        self.ActionHelp = QtGui.QAction(MainWindow)
        self.ActionHelp.setObjectName("ActionHelp")
        self.ActionAbout = QtGui.QAction(MainWindow)
        self.ActionAbout.setObjectName("ActionAbout")
        self.ActionValuesShowHide = QtGui.QAction(MainWindow)
        self.ActionValuesShowHide.setCheckable(True)
        self.ActionValuesShowHide.setChecked(True)
        self.ActionValuesShowHide.setObjectName("ActionValuesShowHide")
        self.ActionMetadataShowHide = QtGui.QAction(MainWindow)
        self.ActionMetadataShowHide.setCheckable(True)
        self.ActionMetadataShowHide.setChecked(True)
        self.ActionMetadataShowHide.setObjectName("ActionMetadataShowHide")
        self.MenuFile.addAction(self.ActionNew)
        self.MenuFile.addAction(self.ActionOpen)
        self.MenuFile.addSeparator()
        self.MenuFile.addAction(self.ActionSave)
        self.MenuFile.addAction(self.ActionSaveAs)
        self.MenuFile.addSeparator()
        self.MenuFile.addAction(self.ActionQuit)
        self.MenuHelp.addAction(self.ActionHelp)
        self.MenuHelp.addSeparator()
        self.MenuHelp.addAction(self.ActionAbout)
        self.MenuImport.addAction(self.ActionImportFromRaster)
        self.MenuImport.addAction(self.ActionImportFromLcc)
        self.MenuBar.addAction(self.MenuFile.menuAction())
        self.MenuBar.addAction(self.MenuImport.menuAction())
        self.MenuBar.addAction(self.MenuHelp.menuAction())
        self.ToolBar.addAction(self.ActionValuesShowHide)
        self.ToolBar.addAction(self.ActionMetadataShowHide)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.ActionValuesShowHide, QtCore.SIGNAL("triggered(bool)"), self.ValuesDock.setVisible)
        QtCore.QObject.connect(self.ActionMetadataShowHide, QtCore.SIGNAL("triggered(bool)"), self.MetadataDock.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Land Cover Classification Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesLabel.setText(QtGui.QApplication.translate("MainWindow", "CLASSES", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesInsertValuesButton.setText(QtGui.QApplication.translate("MainWindow", "Insert Values", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesAddSiblingButton.setText(QtGui.QApplication.translate("MainWindow", "Add Sibling Class", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesAddChildButton.setText(QtGui.QApplication.translate("MainWindow", "Add Child Class", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesEditButton.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesRemoveButton.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.setSortingEnabled(True)
        self.ClassesTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "name", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.ClassesTree.isSortingEnabled()
        self.ClassesTree.setSortingEnabled(False)
        self.ClassesTree.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "wetl", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.topLevelItem(0).setText(1, QtGui.QApplication.translate("MainWindow", "Wetlands", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.topLevelItem(0).child(0).setText(1, QtGui.QApplication.translate("MainWindow", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.topLevelItem(0).child(1).setText(1, QtGui.QApplication.translate("MainWindow", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.topLevelItem(0).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.topLevelItem(0).child(2).setText(1, QtGui.QApplication.translate("MainWindow", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "for", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.topLevelItem(1).setText(1, QtGui.QApplication.translate("MainWindow", "Forest", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.topLevelItem(1).child(0).setText(1, QtGui.QApplication.translate("MainWindow", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.ClassesTree.setSortingEnabled(__sortingEnabled)
        self.MenuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.MenuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.MenuImport.setTitle(QtGui.QApplication.translate("MainWindow", "&Import", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "VALUES", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesIncludeButton.setText(QtGui.QApplication.translate("MainWindow", "Include", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesExcludeButton.setText(QtGui.QApplication.translate("MainWindow", "Exclude", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesAddButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesRemoveButton.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesTree.setSortingEnabled(True)
        self.ValuesTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesTree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesTree.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "excluded", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.ValuesTree.isSortingEnabled()
        self.ValuesTree.setSortingEnabled(False)
        self.ValuesTree.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesTree.topLevelItem(0).setText(1, QtGui.QApplication.translate("MainWindow", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesTree.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesTree.topLevelItem(1).setText(1, QtGui.QApplication.translate("MainWindow", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesTree.topLevelItem(2).setText(0, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesTree.topLevelItem(2).setText(1, QtGui.QApplication.translate("MainWindow", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesTree.topLevelItem(3).setText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesTree.topLevelItem(3).setText(1, QtGui.QApplication.translate("MainWindow", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.ValuesTree.setSortingEnabled(__sortingEnabled)
        self.MetadataDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "METADATA", None, QtGui.QApplication.UnicodeUTF8))
        self.MetadataNameLabel.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.MetadataDescriptionLabel.setText(QtGui.QApplication.translate("MainWindow", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionNew.setText(QtGui.QApplication.translate("MainWindow", "&New...", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionImportFromRaster.setText(QtGui.QApplication.translate("MainWindow", "From Raster...", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionImportFromLcc.setText(QtGui.QApplication.translate("MainWindow", "From LCC File...", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionHelp.setText(QtGui.QApplication.translate("MainWindow", "LCCEditor &Help", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionAbout.setText(QtGui.QApplication.translate("MainWindow", "About LCCEditor", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionValuesShowHide.setText(QtGui.QApplication.translate("MainWindow", "Show/Hide Values", None, QtGui.QApplication.UnicodeUTF8))
        self.ActionMetadataShowHide.setText(QtGui.QApplication.translate("MainWindow", "Show/Hide Metadata", None, QtGui.QApplication.UnicodeUTF8))

import main_rc
